src/app/urls.py
from django.urls import path
from app.views import *

app_name = 'app'

urlpatterns = [
    # url: '/', name = app:home
    path('', HomeView.as_view(), name="home"),
    path('tutor_topic/', TopicView.tutor_topic, name="tutor_topic"),
    path('homepage/', HomeView.as_view(), name="homepage"),
    # path('api_links/', views.AboutView.api_links, name="api_links"),
]

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
]

src/app/models.py
from django.db import models

# Create your models here.
class user_infos(models.Model):
    user_name = models.CharField(max_length=50,default="")
    pass_user = models.CharField(max_length=50,default="")
    user_email = models.EmailField()
    def __str__(self):
        return self.user_name

class tutorial_types(models.Model):
    type_name = models.CharField(max_length=50)
    def __str__(self):
        return self.type_name

class language_types(models.Model):
    language_name = models.CharField(max_length=50)
    def __str__(self):
        return self.language_name   


class suggestions(models.Model):
    suggestor_name = models.CharField(max_length=50,default="anonymous")
    suggestion = models.CharField(max_length=200,default="")
    suggestion_value = models.IntegerField(default=0,primary_key = True)
    def __str__(self):
        return self.suggestion_value

class tutorials_paths(models.Model):
    links_name = models.CharField(max_length=70,blank=True)
    links_path = models.CharField(max_length=300,blank=True)
    type_value = models.ForeignKey(tutorial_types, on_delete=models.CASCADE)
    language_value = models.ForeignKey(language_types, on_delete=models.CASCADE)
    def __str__(self):
        return self.links_path

src/app/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
import requests, json
from rest_framework.views import APIView
from rest_framework.decorators import api_view
from rest_framework.response import Response
from app.serializers import *
import config
from django.views.generic.base import TemplateView
from django.urls import reverse
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication

class HomeView(TemplateView):
    template_name = "app/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        json_data={}
        domain,domain_auth_url = url_endpoint()
        response= requests.get(domain)  
        data_r = response.json()
        context['data_list'] = []
        domain_language=domain+"language"
        chart2_data = []
        context["data_list"].append({"tutorial":data_r,"path_url":domain,"auth_url":domain_auth_url,"path_url_language":domain_language,"Chart_t":chart2_data})
        return context

class TopicView():
    def tutor_topic(request):
        context = { 
               "data_view" : []
        }
        data_r = ""
        type_val_info=0
        if request.method == "POST":
            type_val_info = request.POST.get('type_val')
            type_val_info = int(type_val_info)
        data_r = tutorials_paths.objects.filter(type_value = type_val_info)
        context["data_view"].append({"type_val": type_val_info,"tutor_data":data_r})
        return render(request,"app/tutorials.html",context)

class ApiView(APIView):
    def get(self,request):
        data_r = tutorials_paths.objects.all()
        serial_data = linksSerializer(data_r,many = True)
        return Response(serial_data.data)



def api_links(request):
    context = { 
               "data_view" : []
               
        }
    
    domain = request.get_host()
    domain="http://"+domain+"/tutorials/"
    response = requests.get(domain).json()
    context["data_view"].append({"response": response})
    return render(request, "app/api_links.html",context)

class ApiInfo():
    @api_view(['GET'])
    def values(request,username):
        num=0
        username=str(username)
        data_r = language_types.objects.filter(language_name=username)
        for req in data_r:
            print(req.language_name)
            num=int(req.language_value)
        links_r = tutorials_paths.objects.filter(language_value=num)
        serial_data = linksSerializer(links_r,many = True)
        return Response(serial_data.data)

def values_double(request,language,tutorial):
    context = { 
               "data_view" : []
               
        }
    context["data_view"].append({"language": language,"tutorial": tutorial})
    return render(request, "app/message.html",context)

def host_for_endpoint(request):
    path_url =""
    path_url = request.build_absolute_uri
    return path_url

def url_endpoint():
    domain = "https://linktutor.herokuapp.com/tutorials/"
    domain_auth = "https://linktutor.herokuapp.com/tutorial_insert/"
    return domain,domain_auth

src/templates/app/api_links.html
{% extends 'base.html' %}

{% block content %}

{% load static %} 

<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>

               <!-- lOGO TEXT HERE -->
               <a href="#" class="navbar-brand">TUTOR-SITE-lINKS</a>
          </div>

          <!-- MENU LINKS -->
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-nav-first">
                   
                    <li><a href="{% url 'app:homepage' %}" class="smoothScroll"><b>HOME</b></a></li>
                    
                    
               </ul>

               <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.mdaminul.info/" target="blank"><i class="fa fa-laptop"></i> mdaminul.info</a></li>
               </ul>
          </div>

     </div>
     
</section>

<!-- Courses -->
<section id="courses">
    <div class="container">
         <div class="row">

              <div class="col-md-12 col-sm-12">
                   <div class="section-title">
                        <h2>Popular Courses <small>Upgrade your skills with newest courses</small></h2>
                   </div>

                   <div class="owl-carousel owl-theme owl-courses">
                    {% for user in data_view %}
                    {% for tutor in user.response %}
                        <div class="col-md-4 col-sm-4 " >
                             <div class="item ">
                                  <div class="courses-thumb">
                                       <div class="courses-top">
                                            
                                            <div class="courses-date">
                                                 
                                                 <span><i class="fa fa-money"></i> Free</span>
                                            </div>
                                       </div>

                                       <div class="courses-detail">
                                             <h4><a href="#">Channel name</a></h4>
                                            <h3><a href="#">{{ tutor.links_name }}</a></h3>
                                            <p>Click below to view the tutorials of the channel {{ tutor.links_name }}</p>
                                       </div>

                                       <div class="courses-info">
                                        
                                             
                                             <div class="courses-price" style="float: left;">
                                                  <b><a href="#" target="_blank"><span style="background-color: black;">{{ tutor.language_type }}</span></a></b>
                                             </div>
                                             
                                            <div class="courses-price">
                                                 <b><a href="{{ tutor.links_path }}" target="_blank"><span>See tutorials</span></a></b>
                                            </div>

                                       
                                       </div>
                                  </div>
                             </div>
                        </div>

                        
                        {% endfor %}
                        {% endfor %}   
                        

                   </div>
              
         </div>
    </div>
</section>

</br></br></br>
{% endblock content %}

src/templates/app/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %} 
<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>

               <!-- lOGO TEXT HERE -->
               <a href="#" class="navbar-brand">TUTOR-SITE-lINKS</a>
          </div>

          <!-- MENU LINKS -->
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-nav-first">
                   
                    <li><a href="#" class="smoothScroll">Home</a></li>
                    
                    <li><a href="#courses" class="smoothScroll">Topic</a></li>
                    <li><a href="#feature" class="smoothScroll">API</a></li>
                    <!--
                    <li><a href="{% url 'app:tutor_topic' %}" class="smoothScroll">API_LINKS</a></li>
                    -->
                    <li><a href="#contact" class="smoothScroll">Report</a></li>
                    <li><a href="#last" class="smoothScroll">Contact</a></li>
               </ul>

               <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.mdaminul.info/" target="blank"><i class="fa fa-laptop"></i> mdaminul.info</a></li>
               </ul>
          </div>
          
     </div>
     
</section>
<section id="about">
    <div class="container">
         <div class="row">

              <div class="col-md-6 col-sm-12">
                   <div class="about-info">
                        <h2>Here you can find most popular tutorial's links about different topics</h2>

                        <figure>
                             <span><i class="fa fa-book"></i></span>
                             <figcaption>
                                  <h3>Various topic</h3>
                                  <p style="color: black;">Choose your online tutorial according to your topic</p>
                             </figcaption>
                        </figure>

                        <figure>
                             <span><i class="fa fa-laptop"></i></span>
                             <figcaption>
                                  <h3>API</h3>
                                  <p style="color: black;">We have developed an API. Here you can provide topic name and language to get the most famous tutorials for the topic via REST API</p>
                             </figcaption>
                        </figure>

                        <figure>
                             <span><i class="fa fa-users"></i></span>
                             <figcaption>
                                  <h3>Authentication Token</h3>
                                  <p style="color: black;">You can accsess GET operation. For Other operation you required Authentication Token</p>
                             </figcaption>
                        </figure>
                   </div>
              </div>

              <div class="col-md-offset-1 col-md-4 col-sm-12 " >
                   <div class="entry-form col-12 col-sm-offset-3 col-md-offset-0 col-sm-4 col-md-6" style="background-image: url('{% static "app/img/image/studentlearning.jpg" %}');">
                    <img href="" / >
                   </div>
              </div>
              
         </div>
    </div>
</section>
<!-- Courses -->
<section id="courses">
    <div class="container">
         <div class="row">

              <div class="col-md-12 col-sm-12">
                   <div class="section-title">
                        <h2>Popular Courses <small style="color: blue">Upgrade your skills with newest courses</small></h2>
                   </div>

                   <div class="owl-carousel owl-theme owl-courses">
                    {% for user in data_list %}
                    {% for tutor in user.tutorial %}
                        <div class="col-md-4 col-sm-4 " >
                             <div class="item ">
                                  <div class="courses-thumb">
                                       <div class="courses-top">
                                            <div class="courses-image">
                                                 <img src="{% static "" %}app/img/image/{{tutor.categ_name}}.jpg" class="img-responsive" alt=""  style="height:200px;">
                                            </div>
                                            <div class="courses-date">
                                                 
                                                 <span><i class="fa fa-money"></i> Free</span>
                                            </div>
                                       </div>

                                       <div class="courses-detail">
                                             
                                            <h3><a href="#">{{ tutor.categ_name }}</a></h3>
                                            <p>Click here to see the list of tutorials about {{ tutor.categ_name }}</p>
                                       </div>

                                       <div class="courses-info">
                                        <form action="{% url 'app:tutor_topic' %}" method="POST">
                                             {% csrf_token %}
                                             <input type="number" name= "type_val" value = "{{ tutor.type_value }}" hidden>
                                            <div class="courses-price">
                                                 <b><input type="submit" value="SEE TUTORIALS"></b>
                                            </div>

                                        </form>
                                       </div>
                                  </div>
                             </div>
                        </div>

                        
                        {% endfor %}
                        {% endfor %}   
                        

                   </div>

         </div>
    </div>
</section>
<section id="feature">
         
    <div class="container">
     <div class="section-title " style="text-align: center;">
          <h2>API GUIDELINE <small style="color: blue;">User guideline for API</small></h2>
     </div>
         <div class="row">
              <div class="col-md-12 col-sm-12" >
                  
              <div class=" col-12 col-md-4 " >
                   <div class="feature-thumb col-12 column_p" >
                    <div class="col-12 apiGuidehead" >
                        <h2 style="color: white;">Link Tutor API</h2>
                    </div>
                    <div class="buttonDiv">
                        <h4>Implemented with Django REST framework</h4>
                    </div>
                    <div class="buttonDiv">
                        <p>Provide topic name and language to get the links of tutorial via REST API </p>
                    </div>
                    <div class="buttonDiv">
                        <p ">For POST,PUT,DELETE operation Authentication token required </p>
                    </div>
                    </div>
              </div>

              <div class=" col-12 col-md-4 " >
                   <div class="feature-thumb col-12 column_p" >
                    <div class="col-12 apiGuidehead divDesign" >
                         <h2 style="color: white;" >Endpoints</h2>
                     </div>
                     <div class="buttonDiv divDesign" >
                        <h3 style="font-size: 20px">Endpoints are given below</h3>
                    </div>
                        <div class="buttonDiv divDesign" >
                       <h6 class="col-12"> <a href="{{ data_list.0.path_url}}" target="blank">{{ data_list.0.path_url}}</a></h6>
                    </div>
                       <div class="buttonDiv divDesign" >
                       <h6 > {{ data_list.0.path_url_language}}</h6>
                    </div>
                       <div class="buttonDiv divDesign" >
                       <h6 > <a href="{{ data_list.0.auth_url}}" target="blank">{{ data_list.0.auth_url}}</a></h6>
                    </div>
                    <div class="buttonDiv divDesign" >
                       <h5>Language name will be small letter here</h5>
                   </br>
                     </div>
                    </div>
              </div>

              <div class=" col-12 col-md-4 " >
               <div class="feature-thumb col-12 column_p" >
                <div class="col-12 apiGuidehead divDesign" >
                    <h2 style="color: white;">Client app</h2>
                </div>
                <div class="buttonDiv divDesign" >
                    <h4>Client app with DB</h4>
                </div>
                <div class="buttonDiv divDesign">
                    <p>This application works as client app for API </p>
                </div>
                <div class="buttonDiv divDesign">
                    <p ">The app is invoking data with REST API and showing output with reporting </p>
                </div>
                </div>
          </div>
         </div>
         </div>
    
    </div>
</section>

<section id="contact">
    <div class="container">
     <div class="section-title">
          <h2>REPORTING <small style="color: white;"><b>Information about the tutorial links in this sites</b></small></h2>
     </div>
         <div class="row">
          <div class="col-12">
              <div class="col-12 " >
               <div id="piechart_3d" ></div>
              </div>

              <div class="col-12 ">
               <div id="myChart" ></div>
              
              </div>
          </div>

         </div>
    </div>
</section>

<section id="last">
     
      
 </section>
<script type="text/javascript">
     google.charts.load("current", {packages:["corechart"]});
     google.charts.setOnLoadCallback(drawChart);
     function drawChart() {
       var data = google.visualization.arrayToDataTable([
         ['Tutorials type', 'Numbers'],
         ['Programming',    2],
         ['Cooking',      3],
         ['Language',  1],
         ['Web development', 1],
       ]);

       var options = {
         title: 'Tutorials Type',
         is3D: true,
         radius:50,
         chartArea: {width: 400, height: 300},
       };

       var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
       chart.draw(data, options);
     }
   </script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load("current", {packages:["corechart"]});
      google.charts.setOnLoadCallback(drawChart);
     var qq = [
     ['Language', '', {role: 'style'}],
     ['English', 2, 'fill-color: gray; fill-opacity: 0.2'],
     ['Deutsch', 2, 'fill-color: red; fill-opacity: 0.2'],
     ['Italian', 1, 'fill-color: blue; fill-opacity: 0.2'],
     ['Spanish', 2, 'stroke-color: #703593; fill-color: #C5A5CF'],
     
     ]
     function drawChart() {
     var data = google.visualization.arrayToDataTable(qq);

        var options = {
          title: 'Tutorial Number',
          is3D: true,
         
        };

        var chart = new google.visualization.ColumnChart(document.getElementById('myChart'));
        chart.draw(data, options);
      }
    </script>

{% endblock content %}

src/templates/app/message.html
{% extends 'base.html' %}

{% block content %}

{% load static %} 

<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>

               <!-- lOGO TEXT HERE -->
               <a href="#" class="navbar-brand">TUTOR-SITE-lINKS</a>
          </div>

          <!-- MENU LINKS -->
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-nav-first">
                   
                    <li><a href="{% url 'app:homepage' %}" class="smoothScroll"><b>HOME</b></a></li>
                    
                    
               </ul>

               <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.mdaminul.info/" target="blank"><i class="fa fa-laptop"></i> mdaminul.info</a></li>
               </ul>
          </div>

     </div>
     
</section>

<!-- Courses -->
<section id="courses">
    <div class="container">
         <div class="row">

              <div class="col-md-12 col-sm-12">
                   <div class="section-title">
                        <h2>Popular Courses <small>Upgrade your skills with newest courses</small></h2>
                   </div>
                   {% for user in data_view %}
                    {% for tutor in user.response %}
                   
                    <h1 style="color:red">{{tutor.links_name}}</h1>
                        
                    {% endfor %}
                    {% endfor %}   
                    
               
                 
                 
         </div>
    </div>
</section>

</br></br></br>
{% endblock content %}

src/templates/app/tutorials (copy).html
{% extends 'base.html' %}

{% block content %}

{% load static %} 

<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>

               <!-- lOGO TEXT HERE -->
               <a href="#" class="navbar-brand">TUTOR-SITE-lINKS</a>
          </div>

          <!-- MENU LINKS -->
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-nav-first">
                   
                    <li><a href="{% url 'app:homepage' %}" class="smoothScroll"><b>HOME</b></a></li>
                    
                    
               </ul>

               <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.mdaminul.info/" target="blank"><i class="fa fa-laptop"></i> mdaminul.info</a></li>
               </ul>
          </div>

     </div>
     
</section>

<!-- Courses -->
<section id="courses">
    <div class="container">
         <div class="row">

              <div class="col-md-12 col-sm-12">
                   <div class="section-title">
                        <h2>Popular Courses <small>Upgrade your skills with newest courses</small></h2>
                   </div>

                   <div class="owl-carousel owl-theme owl-courses">
                    {% for user in data_view %}
                    {% for tutor in user.response %}
                        <div class="col-md-4 col-sm-4 " >
                             <div class="item ">
                                  <div class="courses-thumb">
                                       <div class="courses-top">
                                            
                                            <div class="courses-date">
                                                 
                                                 <span><i class="fa fa-money"></i> Free</span>
                                            </div>
                                       </div>

                                       <div class="courses-detail">
                                             <h4><a href="#">Channel name</a></h4>
                                            <h3><a href="#">{{ tutor.links_name }}</a></h3>
                                            <p>Click below to view the tutorials of the channel {{ tutor.links_name }}</p>
                                       </div>

                                       <div class="courses-info">
                                        
                                             
                                             <div class="courses-price" style="float: left;">
                                                  <b><a href="#" target="_blank"><span style="background-color: black;">{{ tutor.language_value }}</span></a></b>
                                             </div>
                                             
                                            <div class="courses-price">
                                                 <b><a href="{{ tutor.links_path }}" target="_blank"><span>See tutorials</span></a></b>
                                            </div>

                                       
                                       </div>
                                  </div>
                             </div>
                        </div>

                        
                        {% endfor %}
                        {% endfor %}   
                        

                   </div>
              
         </div>
    </div>
</section>

</br></br></br>
{% endblock content %}

src/templates/app/tutorials.html
{% extends 'base.html' %}

{% block content %}

{% load static %} 

<section class="navbar custom-navbar navbar-fixed-top" role="navigation">
     <div class="container">

          <div class="navbar-header">
               <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
                    <span class="icon icon-bar"></span>
               </button>

               <!-- lOGO TEXT HERE -->
               <a href="#" class="navbar-brand">TUTOR-SITE-lINKS</a>
          </div>

          <!-- MENU LINKS -->
          <div class="collapse navbar-collapse">
               <ul class="nav navbar-nav navbar-nav-first">
                   
                    <li><a href="{% url 'app:homepage' %}" class="smoothScroll"><b>HOME</b></a></li>
                    
                    
               </ul>

               <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.mdaminul.info/" target="blank"><i class="fa fa-laptop"></i> mdaminul.info</a></li>
               </ul>
          </div>

     </div>
     
</section>

<!-- Courses -->
<section id="courses">
    <div class="container">
         <div class="row">

              <div class="col-md-12 col-sm-12">
                   <div class="section-title">
                        <h2>Popular Courses <small>Upgrade your skills with newest courses</small></h2>
                   </div>

                   <div class="owl-carousel owl-theme owl-courses">
                    {% for user in data_view %}
                    {% for tutor in user.tutor_data %}
                        <div class="col-md-4 col-sm-4 " >
                             <div class="item ">
                                  <div class="courses-thumb">
                                       <div class="courses-top">
                                            
                                            <div class="courses-date">
                                                 
                                                 <span><i class="fa fa-money"></i> Free</span>
                                            </div>
                                       </div>

                                       <div class="courses-detail">
                                             <h4><a href="#">Channel name</a></h4>
                                            <h3><a href="#">{{ tutor.links_name }}</a></h3>
                                            <p>Click below to view the tutorials of the channel {{ tutor.links_name }}</p>
                                       </div>

                                       <div class="courses-info">
                                        
                                             
                                             <div class="courses-price" style="float: left;">
                                                  <b><a href="#" target="_blank"><span style="background-color: black;">{{ tutor.language_value }}</span></a></b>
                                             </div>
                                             
                                            <div class="courses-price">
                                                 <b><a href="{{ tutor.links_path }}" target="_blank"><span>See tutorials</span></a></b>
                                            </div>

                                       
                                       </div>
                                  </div>
                             </div>
                        </div>

                        
                        {% endfor %}
                        {% endfor %}   
                        

                   </div>
              
         </div>
    </div>
</section>

</br></br></br>
{% endblock content %}